version: '3'

env:
  ENV_FILE: .env

dotenv: ['.env']

vars:
  MIGRATIONS_PATH: './migrations'
  DATABASE_URL: 'postgresql://{{.POSTGRES_USER}}:{{.POSTGRES_PASSWORD}}@{{.POSTGRES_HOST}}:{{.POSTGRES_PORT}}/{{.POSTGRES_DB}}?sslmode=disable'

tasks:
  build_go:
    desc: Build proto files for Go.
    cmds:
      - mkdir -p ./build/go
      - PATH="$(go env GOPATH)/bin:$PATH" protoc --proto_path=. --go_out=./build/go --go-grpc_out=./build/go $(find ProductService -name "*.proto")
      - PATH="$(go env GOPATH)/bin:$PATH" protoc --proto_path=. --go_out=./build/go --go-grpc_out=./build/go $(find AuthService -name "*.proto")