syntax = "proto3";

package AuthService.v1;

import "AuthService/v1/types/user_types.proto";
import "AuthService/v1/types/auth_types.proto";

option csharp_namespace = "HailowApiGateway.Protos.AuthService";
option go_package = "AuthService/v1;AuthService";

message ModeratorSignUpResponse {
    AuthService.v1.types.User user = 1;
}

message SellerSignUpResponse {
    AuthService.v1.types.User user = 1;
}

message CustomerSignUpResponse {
    AuthService.v1.types.User user = 1;
}

message SignInResponse {
    AuthService.v1.types.TokenPair tokens = 1;
}

message RefreshTokensResponse {
    string access_token = 1;
}

message ValidateTokenResponse {
    bool is_valid = 1;
}

message LogoutResponse {
    bool success = 1;
}