syntax = "proto3";

package AuthService.v1;

import "AuthService/v1/auth_request.proto";
import "AuthService/v1/auth_response.proto";

option csharp_namespace = "HailowApiGateway.Protos.AuthService";
option go_package = "AuthService/v1;AuthService";

service AuthService {
    rpc SignUp(SignUpRequest) returns (SignUpResponse);
    rpc SignIn(SignInRequest) returns (SignInResponse);
    rpc RefreshTokens(RefreshTokensRequest) returns (RefreshTokensResponse);
    rpc Logout(LogoutRequest) returns (LogoutResponse);

    rpc ValidateToken(ValidateTokenRequest) returns (ValidateTokenResponse);

    rpc GetUserSessions(GetUserSessionsRequest) returns (GetUserSessionsResponse);
    rpc RevokeSession(RevokeSessionRequest) returns (RevokeSessionResponse);
}