syntax = "proto3";

package auth_service;

// C# settings
option csharp_namespace = "HailowApiGateway.Protos";
// Go settings
option go_package = "github.com/hailow/auth-service/proto";

service AuthService {
    rpc Register (RegisterRequest) returns (RegisterResponse);
    rpc Login (LoginRequest) returns (LoginResponse);
}

message RegisterRequest {
    string name = 1;
    string email = 2;
    string password = 3;
}

message RegisterResponse {
    string user_id = 1;
    string name = 2;
    string email = 3;
}

message LoginRequest {
    string email = 1;
    string password = 2;
}

message LoginResponse {
    string user_id = 1;
    string name = 2;
    string email = 3;
    string token = 4;
}
