syntax = "proto3";

package AuthService.v1;

import "AuthService/v1/auth_request.proto";
import "AuthService/v1/auth_response.proto";

option csharp_namespace = "HailowApiGateway.Protos.AuthService";
option go_package = "AuthService/v1;AuthService";

service AuthService {
    rpc CustomerSignUp(CustomerSignUpRequest) returns (CustomerSignUpResponse);
    rpc AdminSignUp(AdminSignUpRequest) returns (AdminSignUpResponse);
    rpc SignIn(SignInRequest) returns (SignInResponse);
    rpc RefreshTokens(RefreshTokensRequest) returns (RefreshTokensResponse);
    rpc Logout(LogoutRequest) returns (LogoutResponse);
    rpc UploadAvatar(UploadAvatarRequest) returns (UploadAvatarResponse);
    rpc UpdateProfile(UpdateProfileRequest) returns (UpdateProfileResponse);
    rpc UpdateDeliveryInfo(UpdateDeliveryInfoRequest) returns (UpdateDeliveryInfoResponse);
    rpc ValidateToken(ValidateTokenRequest) returns (ValidateTokenResponse);
    rpc ResetPassword(ResetPasswordRequest) returns (UpdatePasswordResponse);
    rpc GetProfile(GetProfileRequest) returns (GetProfileResponse);
    rpc DeleteAccount(DeleteAccountRequest) returns (DeleteAccountResponse);
}