syntax = "proto3";

package AuthService.v1.types;

import "google/protobuf/timestamp.proto";
import "AuthService/v1/types/auth_types.proto";

option csharp_namespace = "HailowApiGateway.Protos.AuthService.Types";
option go_package = "AuthService/v1;AuthService";

message User {
    string id = 1;
    string avatar_url = 2;
    string first_name = 3;
    string last_name = 4;
    string email = 5;
    Role role = 6;
    google.protobuf.Timestamp created_at = 7;
    google.protobuf.Timestamp updated_at = 8;
}