syntax = "proto3";

package SellerService.v1.types;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "HailowApiGateway.Protos.SellerService.Types";
option go_package = "SellerService/v1;SellerService";

enum OrganizationForm {
    ORGANIZATION_FORM_UNSPECIFIED = 0;
    LLC = 1; // Limited Liability Company (ООО)
    JSC = 2; // Joint Stock Company (АО)
    OOO = 3; // Open Joint-Stock Company (ПАО)
    IP = 4; // Individual Entrepreneur (ИП)
}

message Seller {
    string id = 1;
    optional string logo_url = 2;
    string store_name = 3;
    string store_description = 4;
    bool is_active = 5;
    string tin = 6;
    string psrn = 7;
    string kpp = 8;
    OrganizationForm organization_form = 9;
    string email = 10;
    string city = 11;
    string street = 12;
    string building = 13;
    google.protobuf.Timestamp created_at = 14;
    google.protobuf.Timestamp updated_at = 15;
}