syntax = "proto3";

package ProductService.v1.types;

import "ProductService/v1/types/category_types.proto";
import "ProductService/v1/types/brand_types.proto";
import "google/protobuf/timestamp.proto";

option csharp_namespace = "HailowApiGateway.Protos.ProductService.Types";
option go_package = "ProductService/v1/types;types";

message CategoryAttribute {
    string key = 1;
    string value = 2;
    google.protobuf.Timestamp created_at = 14;
    google.protobuf.Timestamp updated_at = 15;
}

message ProductVariant {
    string id = 1;
    string sku = 2;
    double price = 3;
    optional int32 stock = 4;
    repeated string photos = 5;
    repeated CategoryAttribute attributes = 6;
    google.protobuf.Timestamp created_at = 14;
    google.protobuf.Timestamp updated_at = 15;
}

message ProductDraft {
    string name = 1;
    optional string description = 2;
    Brand brand = 3;
    Category category = 4;
    repeated ProductVariant variants = 5;
}

message ProductVariantDraft {
    string sku = 1;
    double price = 2;
    optional int32 stock = 3;
    repeated string photos = 4;
    repeated CategoryAttribute attributes = 5;
}

message Product {
    string id = 1;
    string name = 2;
    optional string description = 3;
    Brand brand = 4;
    Category category = 5;
    repeated ProductVariant variants = 6;
    google.protobuf.Timestamp created_at = 7;
    google.protobuf.Timestamp expires_at = 8;
}