syntax = "proto3";

package ProductService.v1;

import "ProductService/v1/types/product_types.proto";

option csharp_namespace = "HailowApiGateway.Protos.ProductService";
option go_package = "ProductService/v1;ProductService";

message CreateResponse {
    types.Product product = 1;
}

message GetResponse {
    types.Product product = 1;
}

message UpdateResponse {
    types.Product product = 1;
}

message ListResponse {
    repeated types.Product products = 1;
    int32 total = 2;
}

message DeleteResponse {
    bool success = 1;
}